apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: default
spec:
  ports:
    - port: 4317
      name: otlp-grpc
    - port: 4318
      name: otlp-http
    - port: 8889
      name: prometheus
  selector:
    app: otel-collector