apiVersion: v1
kind: Service
metadata:
  name: fibonacci-service
  labels:
    app: fibonacci
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30012
      protocol: TCP
      name: http
  selector:
    app: fibonacci